import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-waste',
  templateUrl: './waste.component.html',
  styleUrls: ['./waste.component.css']
})
export class WasteComponent implements OnInit {
  cover= 'assets/img/products/wwt/cover.png'
  img1= 'assets/img/products/wwt/img1.png'
  img2= 'assets/img/products/wwt/img2.png'
  img3= 'assets/img/products/wwt/img3.png'
  img4= 'assets/img/products/wwt/img4.png'
  img5= 'assets/img/products/wwt/img5.png'
  img6= 'assets/img/products/wwt/img6.png'
  img7= 'assets/img/products/wwt/img7.png'
  img8= 'assets/img/products/wwt/img8.png'
  img9= 'assets/img/products/wwt/img9.png'
  img10= 'assets/img/products/wwt/img10.jpg'
  img11= 'assets/img/products/wwt/img11.jpg'
  img12= 'assets/img/products/wwt/img12.png'
  img13= 'assets/img/products/wwt/img13.jpg'
  img14= 'assets/img/products/wwt/img14.jpg'
  img15= 'assets/img/products/wwt/img16.png'
  img16=  'assets/img/products/wwt/img17.png'
  img17=  'assets/img/products/wwt/img18.png'
  img18= 'assets/img/products/wwt/img19.png'
  img19= 'assets/img/products/wwt/img20.png'
  img20= 'assets/img/products/wwt/img21.png'
  img21= 'assets/img/products/wwt/img22.png'
  img22= 'assets/img/products/wwt/img23.png'
  img23= 'assets/img/products/wwt/img15.jpg'
  img24= 'assets/img/products/wwt/img25.png'
  img25= 'assets/img/products/wwt/img26.png'
  img26= 'assets/img/products/wwt/img27.png'
  img27= 'assets/img/products/wwt/img28.jpg'
  img28= 'assets/img/products/wwt/img29.png'
  img29= 'assets/img/products/wwt/img30.png'
  img30= 'assets/img/products/wwt/img31.png'
  img31= 'assets/img/products/wwt/img32.png'
  img32= 'assets/img/products/wwt/img33.png'
  img33= 'assets/img/products/wwt/img34.png'
  img34= 'assets/img/products/wwt/img35.png'
  img35= 'assets/img/products/wwt/img36.png'
  img36= 'assets/img/products/wwt/img37.png'
  img37= 'assets/img/products/wwt/img38.png'
  img38= 'assets/img/products/wwt/img39.png'
  img39= 'assets/img/products/wwt/img40.jpg'
  img40= 'assets/img/products/wwt/img41.jpg'
  img41= 'assets/img/products/wwt/img42.jpg'
  img42= 'assets/img/products/wwt/img43.jpg'
  img43= 'assets/img/products/wwt/img44.png'
  img44= 'assets/img/products/wwt/img45.png'
  img45= 'assets/img/products/wwt/img46.png'
  img46= 'assets/img/products/wwt/img47.png'
  img47= 'assets/img/products/wwt/img48.png'
  img48= 'assets/img/products/wwt/img49.png'
  img49= 'assets/img/products/wwt/img50.png'
  img50= 'assets/img/products/wwt/img51.png'
  img51= 'assets/img/products/wwt/img52.png'
  img52= 'assets/img/products/wwt/img53.png'
  img53= 'assets/img/products/wwt/img54.png'
  img54= 'assets/img/products/wwt/img55.png'
  img56= 'assets/img/products/wwt/img56.jpg'
  img57= 'assets/img/products/wwt/img57.png'
  img58= 'assets/img/products/wwt/img58.png'
  img59= 'assets/img/products/wwt/img59.png'
  img60= 'assets/img/products/wwt/img60.png'
  img61= 'assets/img/products/wwt/img61.png'
  img62= 'assets/img/products/wwt/img62.png'
  img63= 'assets/img/products/wwt/img63.png'
  img64= 'assets/img/products/wwt/img64.png'
  img65= 'assets/img/products/wwt/img65.png'
  img66= 'assets/img/products/wwt/img66.png'
  img67= 'assets/img/products/wwt/img67.jpg'
  img68= 'assets/img/products/wwt/img68.png'
  img69= 'assets/img/products/wwt/img69.png'
  img70= 'assets/img/products/wwt/img70.png'
  img71= 'assets/img/products/wwt/img71.png'
  img72= 'assets/img/products/wwt/img72.png'
  img73= 'assets/img/products/wwt/img73.jpg'
  img74= 'assets/img/products/wwt/img74.png'
  img75= 'assets/img/products/wwt/img75.png'
  img76= 'assets/img/products/wwt/img76.png'
  img77= 'assets/img/products/wwt/img77.png'
  img78= 'assets/img/products/wwt/img78.png'
  img79= 'assets/img/products/wwt/img79.png'
  img80= 'assets/img/products/wwt/img80.png'
  img81= 'assets/img/products/wwt/img81.png'
  img82= 'assets/img/products/wwt/img82.png'




  constructor() { }

  ngOnInit(): void {
  }

}
